[package]
name = "kmip"
version = "0.1.0"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
edition = "2018"
description = "KMIP client library"
repository = "https://github.com/NLnetLabs/kmip/"
license = "BSD-3-Clause"
keywords = ["KMIP", "TTLV", "serde", "serialization"]
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
exclude = ["/.github"]
readme = "README.md"

[dependencies]
enum-display-derive = "0.1.1"
enum-flags = "0.1.6"
kmip-ttlv = "0.1.2"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_bytes = "0.11.5"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "0.7.2"

# for testing tls with openssl
openssl = "0.10.35"

# for testing tls with rustls
rustls = "0.19.1"
rustls-pemfile = "0.2.1"
webpki = "0.21.4"

# for examples/cli-tool
log = "0.4.14"
stderrlog = "0.5.1"
structopt = "0.3.22"
