[package]
name = "krill-kmip-protocol"
version = "0.1.0-dev"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
edition = "2018"
description = "KMIP TTLV message protocol library"
license = "BSD-3-Clause"

[dependencies]
enum-display-derive = "0.1.1"
enum-flags = "0.1.6"
krill-kmip-ttlv = { version = "0.1.0-dev", git = "https://github.com/NLnetLabs/krill-kmip-ttlv.git", branch = "main" }
serde = "1.0.126"
serde_derive = "1.0.126"
serde_bytes = "0.11.5"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "0.7.2"
openssl = "0.10.35"