[package]
name = "kmip-protocol"
version = "0.1.1-dev"
authors = ["The NLnet Labs RPKI Team <rpki-team@nlnetlabs.nl>"]
edition = "2018"
description = "KMIP protocol object (de)serialization"
repository = "https://github.com/NLnetLabs/kmip/"
license = "BSD-3-Clause"
keywords = ["KMIP", "TTLV", "serde", "serialization"]
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
exclude = ["/.github"]
readme = "README.md"
build = "build.rs"

[dependencies]
enum-display-derive = "0.1.1"
enum-flags = "0.1.6"
kmip-ttlv = "0.3.0"
log = "0.4.14"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_bytes = "0.11.5"

[build-dependencies]
rustc_version   = "0.4.0"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "0.7.2"

# for testing tls with openssl
openssl = "0.10.35"

# for testing tls with rustls
rustls = "0.19.1"
rustls-pemfile = "0.2.1"
webpki = "0.21.4"

# for examples/demo
log = "0.4.14"
simple-logging = "2.0.2"
structopt = "0.3.22"
